### ISSUE TITLE
ERROR in: scheme.initial_conditions_from_trajectories()

### ISSUE THREAD

**Issue by SesswireD** [openpathsampling/openpathsampling#1162]
The error that occurs within OPS is:

```
    if self.scalarize_numpy_singletons and results.shape[-1] == 1:
AttributeError: 'list' object has no attribute 'shape'
```

I am trying to start sampling the transition event of dissolved glycine in water into the gamma crystal polymorph. I have an initial trajectory that exhibits this transition. In order to discriminate between the liquid and crystal phases I've implemented a custom order parameter that tracks the size of the largest crystalline cluster. The system is considered to be in the crystal state above a certain cutoff size. The md engine used is GROMACS. The script to run Transition Path Sampling with can be found below together with the complete error output. 

```python
import sys
import os
import itertools
import argparse
import mdtraj as md
import numpy as np
import matplotlib.pyplot as plt
import logging.config
import weakref
import openpathsampling as paths
import pandas as pd
from scipy.spatial import distance_matrix
from scipy.special import sph_harm
from pathlib import Path
from openpathsampling.engines import gromacs as ops_gmx
from datetime import datetime
from openpathsampling.experimental.storage import monkey_patch_all
from openpathsampling.experimental.storage.collective_variables import MDTrajFunctionCV
from openpathsampling.experimental.storage import Storage

#Initializes experimental OPS storage 
print("initializing OPS storage")
paths = monkey_patch_all(paths)


def max_crystal_size(frame):
    """
    Returns the size of the largest crystal nucleus for a given simulation frame

    frame : MDTraj.Trajectory
        Trajectory object of the current frame

    lq6_cutoff : float
        cutoff for the Local Q6 Steinhardt parameter above which atoms are considered crystalline

    d_cutoff : float
        distance cutoff below which atoms are considered close enough
    """

    #Add imports
    import sys
    import os
    import mdtraj as md
    import numpy as np
    import pandas as pd
    from scipy.spatial import distance_matrix
    from scipy.special import sph_harm

    #Function parameters:
    lq6_cutoff = 0.5
    d_cutoff= 0.6

    def compute_neighbor_vectors(coords, box, adjacency_matrix):
        """
        Compute the neighbor vectors for each atom in the system considering periodic boundary conditions (PBC).
        
        Parameters:
            coords (np.ndarray): Array of shape (n_atoms, 3) containing the coordinates of the atoms.
            box (np.ndarray): Array of shape (3,) containing the box dimensions for PBC.
            adjacency_matrix (np.ndarray): Array of shape (n_atoms, n_atoms), where 1 indicates atoms are neighbors.
        
        Returns:
            list of np.ndarray: List where each element contains the bond vectors (n_neighbors, 3) for each atom.
        """
        #Compute pairwise displacement matrix
        n_atoms = coords.shape[0]
        
        #Calculate all pairwise displacements using broadcasting
        displacements = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
        
        #Apply periodic boundary conditions
        displacements -= box * np.round(displacements / box)
        
        #Mask out non-neighbors using the adjacency matrix (neighbors indicated by 1)
        neighbor_vectors = [displacements[i][adjacency_matrix[i] == 1] for i in range(n_atoms)]
        
        return neighbor_vectors


    def compute_q6(neighbor_vectors, l=6):
        """
        Compute the normalized q6 vectors for all atoms in the system.
        
        Parameters:
            neighbor_vectors (list of np.ndarray): A list where each element contains the bond vectors 
                                                (n_neighbors, 3) for each atom.
            l (int): Degree of spherical harmonics (default is 6).
        
        Returns:
            np.ndarray: An array of normalized q6 vectors for all atoms, shape (n_atoms, 2l+1).
        """
        n_atoms = len(neighbor_vectors)
        q6_vectors = np.zeros((n_atoms, 2 * l + 1), dtype=complex)  # Store q6 vector for each atom
        
        #Loop over all atoms
        for i, neighbors in enumerate(neighbor_vectors):
            if neighbors.size == 0:
                continue  # Skip if no neighbors

            #Vectorized spherical coordinate calculation
            r = np.linalg.norm(neighbors, axis=1)
            theta = np.arccos(neighbors[:, 2] / r)
            phi = np.arctan2(neighbors[:, 1], neighbors[:, 0])
            
            #Compute all spherical harmonics at once
            m_values = np.arange(-l, l + 1)
            Y_lm = np.array([sph_harm(m, l, phi, theta) for m in m_values])  # Shape (2l+1, n_neighbors)
            
            #Sum the spherical harmonics for each atom and normalize
            q6_vectors[i, :] = np.sum(Y_lm, axis=1)
            q6_vectors[i, :] /= np.sqrt(np.sum(np.abs(q6_vectors[i, :])**2))  # Normalize the q6 vector
        
        return q6_vectors


    def compute_local_q6(q6_vectors, adjacency_matrix, dist_matrix, cutoff):
        """
        Compute the local Steinhardt Q6 parameter for all atoms in a vectorized manner.
        
        Parameters:
            q6_vectors (np.ndarray): Array of normalized q6 vectors for all atoms, shape (n_atoms, 2l+1).
            adjacency_matrix (np.ndarray): Adjacency matrix indicating neighbors (n_atoms, n_atoms).
            dist_matrix (np.ndarray): Pairwise distance matrix (n_atoms, n_atoms).
            cutoff (float): Distance cutoff for the neighbor interaction.
        
        Returns:
            np.ndarray: An array of local Q6 values for all atoms, shape (n_atoms,).
        """
        #Mask out distances larger than the cutoff
        neighbor_mask = (dist_matrix <= cutoff) & (adjacency_matrix == 1)
        
        #Compute the dot products of q6 vectors for all atoms
        q6_dot_products = np.real(np.einsum('ik,jk->ij', q6_vectors, np.conjugate(q6_vectors)))
        
        #Apply the neighbor mask to the dot products
        q6_weighted_dot_products = q6_dot_products * neighbor_mask
        
        #Compute the numerator (sum of weighted dot products) and denominator (number of neighbors)
        numerator = np.sum(q6_weighted_dot_products, axis=1)
        denominator = np.sum(neighbor_mask, axis=1)
        
        #Prevent division by zero
        denominator[denominator == 0] = 1
        
        #Compute the final local Q6 values
        local_q6_values = numerator / denominator
        
        return local_q6_values


    def pbc_distance_matrix(coords, box_length):
        """
        Compute the pairwise distance matrix with periodic boundary conditions.

        Parameters:
        coords: array_like
            The coordinates of the points (shape: [N, 3]).
        box_length: array_like
            The box lengths in each dimension (shape: [3] for x, y, z).
        
        Returns:
        dist_matrix: array_like
            Pairwise distance matrix with PBC applied (shape: [N, N]).
        """

        #Get number of atoms in the system
        num_atoms = len(coords)

        #Initialize the distance matrix
        dist_matrix = np.zeros((num_atoms, num_atoms))

        #Fill each element in the matrix
        for i in range(num_atoms):
            for j in range(i + 1, num_atoms):
                delta = coords[i] - coords[j]
                #Apply minimum image convention
                delta = delta - box_length * np.round(delta / box_length)
                dist = np.sqrt(np.sum(delta ** 2))
                dist_matrix[i, j] = dist
                dist_matrix[j, i] = dist  # Symmetric matrix
        
        return dist_matrix


    def dfs(node, adj_matrix, visited, cluster):
        """
        Perform DFS to find all nodes connected to the given node.

        Parameters:
            node (int): The current node to start DFS from.
            adj_matrix (np.ndarray): The adjacency matrix representing the graph.
            visited (set): A set of nodes that have already been visited.
            cluster (list): The current cluster being formed.
        """
        visited.add(node)
        cluster.append(node)

        #Traverse all neighbors of the current node
        for neighbor, is_connected in enumerate(adj_matrix[node]):
            if is_connected == 1 and neighbor not in visited:
                dfs(neighbor, adj_matrix, visited, cluster)


    def find_clusters(adj_matrix):
        """
        Find clusters in the graph using DFS.

        Parameters:
            adj_matrix (np.ndarray): The adjacency matrix representing the graph.
        
        Returns:
            list of list: A list of clusters, where each cluster is a list of nodes.
        """
        visited = set()
        clusters = []

        #Iterate through each node in the graph
        for node in range(len(adj_matrix)):
            if node not in visited:
                #If the node is not visited, start a new cluster
                cluster = []
                dfs(node, adj_matrix, visited, cluster)
                clusters.append(cluster)

        return clusters


    def extract_ca_coordinates(frame):
        """
        Returns the coordinates and box vector of the CA atoms for a given simulation frame

        frame : topology
            topology of the current frame
        """

        #Select only CA atoms (alpha carbons)
        ca_atoms = frame.topology.select("name CA")

        #Create a new trajectory object containing only the CA atoms
        ca_frame = frame.atom_slice(ca_atoms)

        #Extract coordinates of CA atoms (from the first and only frame, so we use index 0)
        ca_coordinates = ca_frame.xyz[0].T  # Transpose to separate x, y, z coordinates

        #Extract box sizes of current frame
        box_length = ca_frame.unitcell_lengths[0]

        return ca_coordinates, box_length


    #Get coordinates of CA atoms
    ca_coords, box = extract_ca_coordinates(frame)

    #Get the periodic pairwise distances between atoms matrix
    dist_matrix = pbc_distance_matrix(ca_coords.T, box)

    #Create an adjacency matrix where 1 indicates distance <= cutoff, else 0
    adjacency_matrix = (dist_matrix <= d_cutoff).astype(int)

    #Set the diagonal to 0 (since an atom is not adjacent to itself)
    np.fill_diagonal(adjacency_matrix, 0)

    #Compute the neighbor vectors for each atom
    neighbor_vectors = compute_neighbor_vectors(ca_coords.T, box, adjacency_matrix)

    #Compute Q6 for each atom
    q6_vectors= compute_q6(neighbor_vectors)

    #Compute Local Q6 for each atom
    local_q6_values = compute_local_q6(q6_vectors, adjacency_matrix, dist_matrix, d_cutoff)

    #Select only atoms for which lq6 is high enough
    values_cutoff = np.where(local_q6_values > lq6_cutoff, 1, 0)

    #Remove atoms from adjacency matrix that are not crystalline (select crystal neighbors)
    crystal_filter = np.outer(values_cutoff, values_cutoff)
    crystal_matrix = adjacency_matrix * crystal_filter

    #Find clusters within connected crystal atoms
    connected_components = find_clusters(crystal_matrix)

    #Select largest cluster
    crystal_size = max(connected_components, key=len)

    return crystal_size


def run_TPS(grofile, topfile, mdpfile, pathfile, ops_runs):
    """
    Performs Transition Path Sampling on a glycine nucleation trajectory.

    grofile: path to gro file of trajectory

    topfile: path to top file of trajectory

    mdpfile: path to mdp file of trajectory

    pathfile: file to initial trajectory
    """

    print("settig gmx options")
    #Specify the GROMACS engine options
    options = {'gmx_executable': 'srun --mpi=pmix gmx_mpi -nobackup ',
                'snapshot_timestep': 10.0, #set equal to (dt * nstxout) in .mdp: 10 = 0.002* 5000
                # 'mdrun_args': ' -pin on -ntomp 64 -dlb yes -ntmpi 1 ',
                'base_dir': ".",
                'prefix': "md",
                'n_frames_max': 500   # n_frames_max < (nsteps / nstxout) in mdp: 500 < 50000 = 250000000/ 5000
                }
    
    print('building gmx engine')
    #Build the gromacs md engine
    md_engine = ops_gmx.Engine(gro=grofile,
                                mdp=mdpfile,
                                top=topfile,
                                options=options,
                                base_dir=".",
                                prefix="md").named("engine")

    print("set current snapshot")
    #Get current snapshot to be computed (initializes engine with current snapshot)
    template = md_engine.current_snapshot

    print('pass custom CV to OPS')
    #Wrap custom OrderParameter in OPS MDtrajFunctionCV (assumes input is MDTraj.Trajectory)
    crystal_size = paths.MDTrajFunctionCV("Crystal Size", max_crystal_size, template.topology)
    crystal_size.with_diskcache() #Arjun does this. Why?
    #Wrap custom OrderParameter in OPS CoordinateFunctionCV (assumes input are coordinates)
    # crystal_size = paths.CoordinateFunctionCV("Crystal Size", max_crystal_size, template.topology) 
    #Wrap custom OrderParameter in OPS CustomCV (assumes OPS snapshot)

    #Stable state definitions :
    #Stable crystal has between 280 and 588 glycine molecules
    print("defining stable states")
    crystal = (paths.CVDefinedVolume(crystal_size, 280, 588)).named("crystal")
    #Liquid between 1 and 5
    liquid = (paths.CVDefinedVolume(crystal_size, 1, 10 )).named("liquid")

    print("creating TPS network")
    #Set OPS network (path between stable states)
    network = paths.TPSNetwork(liquid,crystal)

    print("setting shooting scheme")
    #Choose shooting move (shoot from points close the nucleus interface) (l_0=mean, alpha=width)
    scheme = paths.OneWayShootingMoveScheme(network,
                                        selector=paths.GaussianBiasSelector(crystal_size, alpha=50.0, l_0=130.0),
                                        engine = md_engine)

    print("loading initial trajectory")
    #Load the initial trajectory from trr
    initial_path = md.load(pathfile, top=grofile)
    topology = initial_path.topology
    
    print('converting initial trajectory to OPS path')
    #Convert initial trajectory to OPS path (OPS/TPS can't handle pathlib path objects!)
    ops_path = paths.Trajectory([md_engine.read_frame_from_file(str(pathfile), num)
                                   for num in range(len(initial_path.xyz))])

    print("getting initial conditions from OPS path")
    #Initial Conditions
    initial_conditions = scheme.initial_conditions_from_trajectories(ops_path)

    print("setting storage")
    #Storage 
    paths.InterfaceSet.simstore = True
    if cyc_no:
        fname = Path(out_path / f'{file_name}_{run_id}_{str(cyc_no).zfill(2)}').with_suffix('.db')
    else:
        fname = Path(out_path / f'{file_name}_{run_id}').with_suffix('.db')
    storage = Storage(str(fname), 'w')

    print("initializing OPS sampler")
    #Initialize OPS sampler
    sampler = paths.PathSampling(storage, move_scheme=scheme, sample_set=initial_conditions)

    print("running OPS")
    #Run the OPS sampler for ops_runs
    sampler.run(ops_runs)


#PARAMETERS
pathfile = "nucleation_trajectory.trr"
grofile = "nucleation_trajectory.gro"
topfile = "nucleation_trajectory.top"
mdpfile = "inputParameters.mdp"
ops_runs = 2

#Run Transition Path Sampling for ops_runs
run_TPS(grofile, topfile, mdpfile, pathfile, ops_runs)

```

I've checked to see whether this problem arises due to a mistake in my custom Collective Variable, but this does not seem to be the case. The complete error output is:

```
getting initial conditions from OPS path
# trying strategy #1 `get`: still missing 1 samples
?
Traceback (most recent call last):
  File "/state/partition1/sesswired/144759/glycine_tps_gro_new.py", line 388, in <module>
    run_TPS(grofile, topfile, mdpfile, pathfile, ops_runs)
  File "/state/partition1/sesswired/144759/glycine_tps_gro_new.py", line 360, in run_TPS
    initial_conditions =scheme.initial_conditions_from_trajectories(ops_path)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/high_level/move_scheme.py", line 600, in initial_conditions_from_trajectories
    sample_set = sample_set.generate_from_trajectories(
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/sample.py", line 587, in generate_from_trajectories
    sample = ens.get_sample_from_trajectories(
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 829, in get_sample_from_trajectories
    if self(traj):
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 1619, in __call__
    transitions = self.transition_frames(trajectory, trusted)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 1589, in transition_frames
    subtraj_final = self._find_subtraj_final(trajectory,
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 1678, in _find_subtraj_final
    while ((ens.can_append(subtraj, trusted=True) or
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 1376, in can_append
    return self._generalized_short_circuit(
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 1342, in _generalized_short_circuit
    a = f1(trajectory, trusted)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 2237, in can_append
    return self._trusted_call(trajectory, self._cache_can_append)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/ensemble.py", line 2227, in _trusted_call
    cache.contents['previous'] = self._volume(frame)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/volume.py", line 424, in __call__
    l = self._get_cv_float(snapshot)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/volume.py", line 418, in _get_cv_float
    val = self.collectivevariable(snapshot)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 229, in __getitem__
    return self._post[items]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 242, in __getitem__
    return np.array(self._post[items])
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 260, in __getitem__
    return self._post[[items]][0]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 74, in __getitem__
    rep = list(self._post[nones])
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 67, in __getitem__
    results = self._get_list(items)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 361, in _get_list
    if self.scalarize_numpy_singletons and results.shape[-1] == 1:
AttributeError: 'list' object has no attribute 'shape'
```

 Any advice would be greatly appreciated.

**Comment by SesswireD** [comment]
The error did come from my custom CV. By accident it outputted a list (atom indices of the largest crystal) instead of returning the length of this list (i.e. the size of the crystal).

**Comment by sroet** [comment]
Dear @SesswireD,

The error that pops up is unclear, but stems from you changing to a `MDTrajFunctionCV` instead of `CoordinateFunctionCV`. 

An `MDTrajFunctionCV` not only assumes your function takes an `MDTraj.Trajectory`, but also that it behaves like an `MDTraj` function. In this case we expect your function to return a numpy array, like all functions of `MDTraj` do.

Another option could be to reset the wrapper defaults to the ones from `CoordinateFunctionCV`:
```python
    crystal_size = paths.MDTrajFunctionCV("Crystal Size", max_crystal_size, template.topology, cv_wrap_numpy_array=False, cv_scalarize_numpy_singletons=False)
```

**Comment by SesswireD** [comment]
Dear @sroet ,

Thank you very much for your response. Indeed, I had missed that the output of my custom `MDTrajFunctionCV` should be a numpy array. I managed to fix the issue this morning by leaving the wrapper defaults as is, but wrapping the output of my CV in an array like:

```python
return np.array([[crystal_size]])
```

The script works perfectly now and has finished a few cycles of TPS.

**Comment by sroet** [comment]
> The script works perfectly now and has finished a few cycles of TPS.

Good to hear! I will close this issue, but feel free to reopen if you don't think this issue is resolved.

**Comment by SesswireD** [comment]
Well, I have another issue related to the custom `MDTrajFunctionCV`. After having successfully run 2 TPS cycles using the above script I want to continue to run more cycles. To achieve this I run:

```python
import openpathsampling as paths
from openpathsampling.experimental.storage import Storage

#Open the storage file in append mode (it's already using SimStore)
storage = Storage("tps_test.db", "a")

#Load the PathSampling object from the storage
tps_sampler = storage.pathsimulators[0]

#Restart the simulation at the last step
tps_sampler.restart_at_step(storage.steps[-1])

#Run additional cycles
tps_sampler.run(100)

#Close the storage
storage.close()
```

Which was taken from [here](http://openpathsampling.org/latest/examples/restarting.html). The script correctly resumes the sampling at cycle 3, but then quickly halts with the following message:

```
Working on Monte Carlo cycle number 3
Starting simulation...
Working on first step
Traceback (most recent call last):
  File "/state/partition1/sesswired/144937/continue_tps.py", line 14, in <module>
    tps_sampler.run(100)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathsimulators/path_sampling.py", line 261, in run
    hook_state, mcstep = self.run_one_step(step_info, hook_state)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathsimulators/path_sampling.py", line 291, in run_one_step
    movepath = self._mover.move(self.sample_set, step=self.step)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 2635, in move
    self.mover.move(sample_set),
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 1605, in move
    subchange = mover.move(sample_set)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 1605, in move
    subchange = mover.move(sample_set)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 1605, in move
    subchange = mover.move(sample_set)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 619, in move
    change = self.move_core(samples)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 646, in move_core
    trials, call_details = self(*samples)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/pathmover.py", line 790, in __call__
    shooting_index = self.selector.pick(initial_trajectory)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/shooting.py", line 82, in pick
    prob_list = self._biases(trajectory)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/shooting.py", line 52, in _biases
    return [self.f(s, trajectory) for s in trajectory]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/shooting.py", line 52, in <listcomp>
    return [self.f(s, trajectory) for s in trajectory]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/shooting.py", line 130, in f
    l_s = self.collectivevariable(snapshot)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 229, in __getitem__
    return self._post[items]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 242, in __getitem__
    return np.array(self._post[items])
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 260, in __getitem__
    return self._post[[items]][0]
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 74, in __getitem__
    rep = list(self._post[nones])
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 67, in __getitem__
    results = self._get_list(items)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/netcdfplus/chaindict.py", line 359, in _get_list
    results = self._eval(items)
  File "/home/sesswired/micromamba/envs/ops/lib/python3.9/site-packages/openpathsampling/collectivevariable.py", line 571, in _eval
    return self.cv_callable(t, **self.kwargs)
TypeError: 'dict' object is not callable
```
Any idea how to resolve this?

**Comment by sroet** [comment]
That is an error I am less familiar with (it has been a long time since I programmed for OPS), but I am pretty sure you also need to run the `paths = monkey_patch_all(paths)` part for the storage to keep working as expected. Please let me know if that doesn't work

**Comment by dwhswenson** [comment]
Travel yesterday/conference now, but let me give a very quick answer (only having skimmed most recent comments). The most important problem here is that you're mixing SimStore CVs and old (netcdfplus) CVs. You're intending to use the new CVs (which work with SimStore), and that's definitely recommended. However, there's a tiny mistake in your code: when you wrap your CV in an `MDTrajCVFunction`, you use `paths.MDTrajCVFunction`, which is the old version (the one you want to use is available as plain `MDTrajCVFunction`, no `paths.` at the beginning).

(Re-reading last comments; looks like you found the info of this paragraph; including for completeness): For the original problem, what you're seeing has to do with your custom CV not acting like an MDTraj function. Keep in mind that MDTraj always takes in a trajectory, so we expect it to always return an array of values (one for each frame). So the MDTrajCVFunction wrapper will try to unwrap that into a single value if there is only one value in the array. You're returning an `int`, so it can't do that.

Returning a length-1 numpy array (`return np.array([crystal_size])` should fix it -- at worst, try `return np.array([[crystal_size]])`). This should help with either CV version. The things @sroet mentioned are specific to the old style. See differences between old CVs and new CVs under cell 6 in the [storage example notebook](https://github.com/dwhswenson/ops-storage-notebooks/blob/master/examples/01_simple_usage.ipynb).

That may cause an error with the `use_diskcache` line, because I think that's is functionality from the old form of CV that been replaced by other approaches (essentially, much better defaults) in the new CVs. (If you do not want to save calculated results to disk with the new CVs, you would change the CV's `mode` attribute. Your CV looks very expensive; you want to cache it whenever possible, which is the default for new CVs.)

(Spliced together from some stuff I drafted which in the air last night but failed to send; while listening to a presentation; hope it makes sense, and let me know if anything else is needed!)

**Comment by SesswireD** [comment]
Dear @dwhswenson,

Thank you so much for this elaborate response. Yesterday I tried continuing the TPS runs with the addition of

```python
paths = monkey_patch_all(paths)
``` 

to the script. This seemed to have done the trick; the script finished 20 more cycles last night without any problems.

I did not change `paths.MDTrajCVFunction` to `MDTrajCVFunction` in the first script yet. If I run into problems later or start a new run I will try this and report back.

**Comment by SesswireD** [comment]
I started a new TPS run and changed the old CV definition

```python
#Wrap custom OrderParameter in OPS MDtrajFunctionCV (assumes input is MDTraj.Trajectory)
crystal_size = paths.MDTrajFunctionCV("Crystal Size", max_crystal_size, template.topology)
crystal_size.with_diskcache()
```
to the new CV definition

```python
#Wrap custom OrderParameter in OPS MDtrajFunctionCV (assumes input is MDTraj.Trajectory)
crystal_size = MDTrajFunctionCV(max_crystal_size, template.topology).named("crystal_size")
```

This works as well. However, I noticed that every cycle is reported to start from the same point:

```
Using frame at t = 0 ps

Starting time for run is 0 ps
```

I will open a new issue if I can't find a solution.
