### ISSUE TITLE
Build failures for master

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#583]
https://travis-ci.org/openpathsampling/openpathsampling#L1304-L1329
```
The command "conda install --yes jupyter nose nose-timer python-coveralls msmbuilder pyemma ipynbtest" exited with 0.
3.08s$ source devtools/ci/git_hash.sh
/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/__init__.py", line 33, in <module>
    from analysis.move_scheme import (
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/analysis/__init__.py", line 1, in <module>
    from histogram import Histogram, SparseHistogram, HistogramPlotter2D
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/analysis/histogram.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/travis/miniconda2/envs/test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
Installed version  from git commit hash c603b3f01f86712ee6f9d292bfae57a6e78c3094
```
This doesn't appear to be a sporadic travis failure.

**Comment by dwhswenson** [comment]
Yeah, @jhprinz texted me about this last night. This appears to be an upstream issue: `conda`'s Qt updated from 4.8.7 to 5.6.0, and matplotlib specifically requires Qt 4.

Solution (coming in a PR soon) is to fix `pyqt` to 4 for now, as in https://github.com/ContinuumIO/anaconda-issues/issues/1065. Hopefully, `matplotlib` will update soon to fix the incompatibility: https://github.com/matplotlib/matplotlib/issues/7124 (that issue is only a half-hour old as of now, so they obviously haven't had time to address it!)

**Comment by jchodera** [comment]
Thanks!
